language: java
jdk:
  - oraclejdk8
branches:
  only:
    - master
    - develop
script:
  - "mvn verify"

# Heroku Apps: 
#   fran-backend CICD [Github > Travis > Heroku]
# - [Github       ] Login con dmerniestic1987
# - [Travis-ci.com] Login com github de dmerniestic1987
# - [Heroku       ] Login com diego.alejandro.mernies@gmail.com
deploy:
  provider: heroku
  api_key:
    secure: a044f557-9c08-4626-8b73-c29df99660cd
  app: 
    master: fran-backend-master
    develop: fran-backend-develop
  on:
    repo: dmerniestic1987/fran-backend

notifications:
  email:
    on_failure: change
    on_success: change


